### ISSUE TITLE
MaryTTS-compatible /process endpoint issue with Home Assistant

### ISSUE THREAD

**Issue by mikeygnyc** [synesthesiam/docker-mozillatts#8]
I'm experiencing a bit of an issue with Home Assistant calling the MaryTTS API. Right now I do get a wave file output from the server but it appears to be concatenating all the input parameters as the string to synthesize. HA appears to want to use the POST method so if I were to try and have HA speak "Hello", it would actually speak "INPUT_TEXT=Hello&INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&LOCALE=en_US&AUDIO=WAVE_FILE&VOICE=cmu-slt-hsmm". I'm not sure if this is an HA config issue or a server config issue. Right now my HA config for tts looks something like this:

```
tts:
  - platform: marytts
    port: 59125
    host: [redacted]
    base_url: https://[redacted]:8123

```
